plugins {
	id 'application'
	id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
	mavenCentral()
	maven {
		url "https://plugins.gradle.org/m2/"
		url "https://jogamp.org/deployment/maven"
	}
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

javafx {
	version = '22.0.1'
	modules = [ 'javafx.controls', 'javafx.swing' ]
}

import org.gradle.internal.os.OperatingSystem

project.ext.lwjglVersion = "3.3.4"

switch (OperatingSystem.current()) {
	case OperatingSystem.LINUX:
		project.ext.lwjglNatives = "natives-linux"
		def osArch = System.getProperty("os.arch")
		if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
			project.ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
		} else if  (osArch.startsWith("ppc")) {
			project.ext.lwjglNatives += "-ppc64le"
		} else if  (osArch.startsWith("riscv")) {
			project.ext.lwjglNatives += "-riscv64"
		}
		break
	case OperatingSystem.WINDOWS:
		project.ext.lwjglNatives = "natives-windows"
		break
}

dependencies {
	implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

	implementation "org.lwjgl:lwjgl"
	implementation "org.lwjgl:lwjgl-openal"
	implementation "org.lwjgl:lwjgl-stb"
	runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
	runtimeOnly "org.lwjgl:lwjgl-openal::$lwjglNatives"
	runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"

	implementation 'org.jogamp.gluegen:gluegen-rt-main:2.5.0'
	implementation 'org.jogamp.joal:joal-main:2.5.0'
}

sourceSets {
	main {
		java {
			srcDir 'src'
		}
		resources {
			srcDir 'res'
		}
	}
}

jar {
	manifest {
		attributes 'Main-Class': 'com.zandgall.csc322.finalproj.Main'
	}
}

application {
	mainClass = 'com.zandgall.csc322.finalproj.Main'
}
